<?php
if ($block->isBlockEnabled()) :
    $productIds = $block->getFeaturedProductIds();
    foreach ($productIds as $productId) :
        $product = $block->loadProductById($productId);
        if ($product) :
?>
            <div class="product-featured">
                <h2>Produto em Destaque</h2>
                <div>
                    <img src="<?php echo $block->getImageUrl($product); ?>" alt="<?php echo $product->getName(); ?>">
                    <p><?php echo $product->getName(); ?></p>
                    <p>Valor <?php echo $block->getPrice($product); ?></p>
                    <p>Estoque <?php echo $block->getStockQuantity($product); ?></p>
                </div>
            </div>
<?php
        endif;
    endforeach;
endif;
?>
